/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const input: string;
declare const noBorder: string;
declare const sizeXs: string;
declare const sizeSm: string;
declare const sizeMd: string;
declare const radiusNone: string;

export {
	input,
	noBorder as "no-border",
	sizeXs as "size-xs",
	sizeSm as "size-sm",
	sizeMd as "size-md",
	radiusNone as "radius-none"
};

declare const __default_export__: {
	input: typeof input;
	"no-border": typeof noBorder;
	"size-xs": typeof sizeXs;
	"size-sm": typeof sizeSm;
	"size-md": typeof sizeMd;
	"radius-none": typeof radiusNone;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5wdXQubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJpbnB1dC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBRUE7Y0FrQ0c7Y0FJQTtjQUtBO2NBS0E7Y0FLQTs7O0NBckRIO0NBa0NHO0NBSUE7Q0FLQTtDQUtBO0NBS0E7Ozs7Q0FyREg7Ozs7Ozs7In0=
