/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as baseRouteRouteImport } from './routes/(base)/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as baseIndexRouteImport } from './routes/(base)/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as baseAccountIndexRouteImport } from './routes/(base)/account/index'

const baseRouteRoute = baseRouteRouteImport.update({
  id: '/(base)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const baseIndexRoute = baseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => baseRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const baseAccountIndexRoute = baseAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => baseRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof baseIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account/': typeof baseAccountIndexRoute
}
export interface FileRoutesByTo {
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof baseIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/account': typeof baseAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(base)': typeof baseRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(base)/': typeof baseIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/(base)/account/': typeof baseAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/admin/'
    | '/auth/'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/signin' | '/auth/signup' | '/' | '/admin' | '/auth' | '/account'
  id:
    | '__root__'
    | '/(base)'
    | '/admin'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/(base)/'
    | '/admin/'
    | '/auth/'
    | '/(base)/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  baseRouteRoute: typeof baseRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(base)': {
      id: '/(base)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof baseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(base)/': {
      id: '/(base)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof baseIndexRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(base)/account/': {
      id: '/(base)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof baseAccountIndexRouteImport
      parentRoute: typeof baseRouteRoute
    }
  }
}

interface baseRouteRouteChildren {
  baseIndexRoute: typeof baseIndexRoute
  baseAccountIndexRoute: typeof baseAccountIndexRoute
}

const baseRouteRouteChildren: baseRouteRouteChildren = {
  baseIndexRoute: baseIndexRoute,
  baseAccountIndexRoute: baseAccountIndexRoute,
}

const baseRouteRouteWithChildren = baseRouteRoute._addFileChildren(
  baseRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  baseRouteRoute: baseRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
