/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as baseRouteRouteImport } from './routes/(base)/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as baseIndexRouteImport } from './routes/(base)/index'
import { Route as baseAccountRouteRouteImport } from './routes/(base)/account/route'
import { Route as basePlayRouteImport } from './routes/(base)/play'
import { Route as basePlayGraderRouteImport } from './routes/(base)/play-grader'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as baseAccountIndexRouteImport } from './routes/(base)/account/index'
import { Route as baseAccountSecurityRouteImport } from './routes/(base)/account/security'
import { Route as baseProfileUsernameRouteImport } from './routes/(base)/profile/$username'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminUserIdRouteImport } from './routes/admin/user/$id'

const baseRouteRoute = baseRouteRouteImport.update({
  id: '/(base)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const baseIndexRoute = baseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => baseRouteRoute,
} as any)
const baseAccountRouteRoute = baseAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => baseRouteRoute,
} as any)
const basePlayRoute = basePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => baseRouteRoute,
} as any)
const basePlayGraderRoute = basePlayGraderRouteImport.update({
  id: '/play-grader',
  path: '/play-grader',
  getParentRoute: () => baseRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const baseAccountIndexRoute = baseAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => baseAccountRouteRoute,
} as any)
const baseAccountSecurityRoute = baseAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => baseAccountRouteRoute,
} as any)
const baseProfileUsernameRoute = baseProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => baseRouteRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdRoute = AdminUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/account': typeof baseAccountRouteRouteWithChildren
  '/play': typeof basePlayRoute
  '/play-grader': typeof basePlayGraderRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof baseIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account/security': typeof baseAccountSecurityRoute
  '/profile/$username': typeof baseProfileUsernameRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/account/': typeof baseAccountIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
}
export interface FileRoutesByTo {
  '/play': typeof basePlayRoute
  '/play-grader': typeof basePlayGraderRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof baseIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/account/security': typeof baseAccountSecurityRoute
  '/profile/$username': typeof baseProfileUsernameRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/account': typeof baseAccountIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(base)': typeof baseRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(base)/account': typeof baseAccountRouteRouteWithChildren
  '/(base)/play': typeof basePlayRoute
  '/(base)/play-grader': typeof basePlayGraderRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(base)/': typeof baseIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/(base)/account/security': typeof baseAccountSecurityRoute
  '/(base)/profile/$username': typeof baseProfileUsernameRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/(base)/account/': typeof baseAccountIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/account'
    | '/play'
    | '/play-grader'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/admin/'
    | '/auth/'
    | '/account/security'
    | '/profile/$username'
    | '/admin/user/$id'
    | '/account/'
    | '/admin/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/play'
    | '/play-grader'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/admin'
    | '/auth'
    | '/account/security'
    | '/profile/$username'
    | '/admin/user/$id'
    | '/account'
    | '/admin/user'
  id:
    | '__root__'
    | '/(base)'
    | '/admin'
    | '/auth'
    | '/(base)/account'
    | '/(base)/play'
    | '/(base)/play-grader'
    | '/auth/signin'
    | '/auth/signup'
    | '/(base)/'
    | '/admin/'
    | '/auth/'
    | '/(base)/account/security'
    | '/(base)/profile/$username'
    | '/admin/user/$id'
    | '/(base)/account/'
    | '/admin/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  baseRouteRoute: typeof baseRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(base)': {
      id: '/(base)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof baseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(base)/': {
      id: '/(base)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof baseIndexRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/(base)/account': {
      id: '/(base)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof baseAccountRouteRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/(base)/play': {
      id: '/(base)/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof basePlayRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/(base)/play-grader': {
      id: '/(base)/play-grader'
      path: '/play-grader'
      fullPath: '/play-grader'
      preLoaderRoute: typeof basePlayGraderRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(base)/account/': {
      id: '/(base)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof baseAccountIndexRouteImport
      parentRoute: typeof baseAccountRouteRoute
    }
    '/(base)/account/security': {
      id: '/(base)/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof baseAccountSecurityRouteImport
      parentRoute: typeof baseAccountRouteRoute
    }
    '/(base)/profile/$username': {
      id: '/(base)/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof baseProfileUsernameRouteImport
      parentRoute: typeof baseRouteRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/user'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user/$id': {
      id: '/admin/user/$id'
      path: '/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof AdminUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface baseAccountRouteRouteChildren {
  baseAccountSecurityRoute: typeof baseAccountSecurityRoute
  baseAccountIndexRoute: typeof baseAccountIndexRoute
}

const baseAccountRouteRouteChildren: baseAccountRouteRouteChildren = {
  baseAccountSecurityRoute: baseAccountSecurityRoute,
  baseAccountIndexRoute: baseAccountIndexRoute,
}

const baseAccountRouteRouteWithChildren =
  baseAccountRouteRoute._addFileChildren(baseAccountRouteRouteChildren)

interface baseRouteRouteChildren {
  baseAccountRouteRoute: typeof baseAccountRouteRouteWithChildren
  basePlayRoute: typeof basePlayRoute
  basePlayGraderRoute: typeof basePlayGraderRoute
  baseIndexRoute: typeof baseIndexRoute
  baseProfileUsernameRoute: typeof baseProfileUsernameRoute
}

const baseRouteRouteChildren: baseRouteRouteChildren = {
  baseAccountRouteRoute: baseAccountRouteRouteWithChildren,
  basePlayRoute: basePlayRoute,
  basePlayGraderRoute: basePlayGraderRoute,
  baseIndexRoute: baseIndexRoute,
  baseProfileUsernameRoute: baseProfileUsernameRoute,
}

const baseRouteRouteWithChildren = baseRouteRoute._addFileChildren(
  baseRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserIdRoute: typeof AdminUserIdRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUserIdRoute: AdminUserIdRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  baseRouteRoute: baseRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
