/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as authedbaseRouteRouteImport } from './routes/(authed)/(base)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as authedbaseIndexRouteImport } from './routes/(authed)/(base)/index'
import { Route as authedbaseAccountRouteRouteImport } from './routes/(authed)/(base)/account/route'
import { Route as authedbasePlayRouteImport } from './routes/(authed)/(base)/play'
import { Route as authedbasePlayGraderRouteImport } from './routes/(authed)/(base)/play-grader'
import { Route as authedSessionIdRouteImport } from './routes/(authed)/session/$id'
import { Route as AdminCourseIndexRouteImport } from './routes/admin/course/index'
import { Route as AdminCourseIdRouteImport } from './routes/admin/course/$id'
import { Route as AdminCourseCreateRouteImport } from './routes/admin/course/create'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminUserIdRouteImport } from './routes/admin/user/$id'
import { Route as authedbaseAccountIndexRouteImport } from './routes/(authed)/(base)/account/index'
import { Route as authedbaseAccountSecurityRouteImport } from './routes/(authed)/(base)/account/security'
import { Route as authedbaseAccountTransactionsRouteImport } from './routes/(authed)/(base)/account/transactions'
import { Route as authedbaseLessonLessonIdRouteImport } from './routes/(authed)/(base)/lesson/$lessonId'
import { Route as authedbaseProfileUsernameRouteImport } from './routes/(authed)/(base)/profile/$username'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authedbaseRouteRoute = authedbaseRouteRouteImport.update({
  id: '/(base)',
  getParentRoute: () => authedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const authedbaseIndexRoute = authedbaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedbaseRouteRoute,
} as any)
const authedbaseAccountRouteRoute = authedbaseAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => authedbaseRouteRoute,
} as any)
const authedbasePlayRoute = authedbasePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => authedbaseRouteRoute,
} as any)
const authedbasePlayGraderRoute = authedbasePlayGraderRouteImport.update({
  id: '/play-grader',
  path: '/play-grader',
  getParentRoute: () => authedbaseRouteRoute,
} as any)
const authedSessionIdRoute = authedSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => authedRouteRoute,
} as any)
const AdminCourseIndexRoute = AdminCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCourseIdRoute = AdminCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCourseCreateRoute = AdminCourseCreateRouteImport.update({
  id: '/course/create',
  path: '/course/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdRoute = AdminUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authedbaseAccountIndexRoute = authedbaseAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedbaseAccountRouteRoute,
} as any)
const authedbaseAccountSecurityRoute =
  authedbaseAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => authedbaseAccountRouteRoute,
  } as any)
const authedbaseAccountTransactionsRoute =
  authedbaseAccountTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => authedbaseAccountRouteRoute,
  } as any)
const authedbaseLessonLessonIdRoute =
  authedbaseLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => authedbaseRouteRoute,
  } as any)
const authedbaseProfileUsernameRoute =
  authedbaseProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => authedbaseRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account': typeof authedbaseAccountRouteRouteWithChildren
  '/play': typeof authedbasePlayRoute
  '/play-grader': typeof authedbasePlayGraderRoute
  '/session/$id': typeof authedSessionIdRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/': typeof authedbaseIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/account/security': typeof authedbaseAccountSecurityRoute
  '/account/transactions': typeof authedbaseAccountTransactionsRoute
  '/lesson/$lessonId': typeof authedbaseLessonLessonIdRoute
  '/profile/$username': typeof authedbaseProfileUsernameRoute
  '/account/': typeof authedbaseAccountIndexRoute
}
export interface FileRoutesByTo {
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/play': typeof authedbasePlayRoute
  '/play-grader': typeof authedbasePlayGraderRoute
  '/session/$id': typeof authedSessionIdRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/': typeof authedbaseIndexRoute
  '/admin/course': typeof AdminCourseIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/account/security': typeof authedbaseAccountSecurityRoute
  '/account/transactions': typeof authedbaseAccountTransactionsRoute
  '/lesson/$lessonId': typeof authedbaseLessonLessonIdRoute
  '/profile/$username': typeof authedbaseProfileUsernameRoute
  '/account': typeof authedbaseAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authed)': typeof authedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(authed)/(base)': typeof authedbaseRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/(authed)/(base)/account': typeof authedbaseAccountRouteRouteWithChildren
  '/(authed)/(base)/play': typeof authedbasePlayRoute
  '/(authed)/(base)/play-grader': typeof authedbasePlayGraderRoute
  '/(authed)/session/$id': typeof authedSessionIdRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/user/$id': typeof AdminUserIdRoute
  '/(authed)/(base)/': typeof authedbaseIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/(authed)/(base)/account/security': typeof authedbaseAccountSecurityRoute
  '/(authed)/(base)/account/transactions': typeof authedbaseAccountTransactionsRoute
  '/(authed)/(base)/lesson/$lessonId': typeof authedbaseLessonLessonIdRoute
  '/(authed)/(base)/profile/$username': typeof authedbaseProfileUsernameRoute
  '/(authed)/(base)/account/': typeof authedbaseAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/'
    | '/auth/'
    | '/account'
    | '/play'
    | '/play-grader'
    | '/session/$id'
    | '/admin/course/$id'
    | '/admin/course/create'
    | '/admin/user/$id'
    | '/'
    | '/admin/course/'
    | '/admin/user/'
    | '/account/security'
    | '/account/transactions'
    | '/lesson/$lessonId'
    | '/profile/$username'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/signin'
    | '/auth/signup'
    | '/admin'
    | '/auth'
    | '/play'
    | '/play-grader'
    | '/session/$id'
    | '/admin/course/$id'
    | '/admin/course/create'
    | '/admin/user/$id'
    | '/'
    | '/admin/course'
    | '/admin/user'
    | '/account/security'
    | '/account/transactions'
    | '/lesson/$lessonId'
    | '/profile/$username'
    | '/account'
  id:
    | '__root__'
    | '/(authed)'
    | '/admin'
    | '/auth'
    | '/(authed)/(base)'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/'
    | '/auth/'
    | '/(authed)/(base)/account'
    | '/(authed)/(base)/play'
    | '/(authed)/(base)/play-grader'
    | '/(authed)/session/$id'
    | '/admin/course/$id'
    | '/admin/course/create'
    | '/admin/user/$id'
    | '/(authed)/(base)/'
    | '/admin/course/'
    | '/admin/user/'
    | '/(authed)/(base)/account/security'
    | '/(authed)/(base)/account/transactions'
    | '/(authed)/(base)/lesson/$lessonId'
    | '/(authed)/(base)/profile/$username'
    | '/(authed)/(base)/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRouteRoute: typeof authedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/(base)': {
      id: '/(authed)/(base)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedbaseRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(authed)/(base)/': {
      id: '/(authed)/(base)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedbaseIndexRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
    '/(authed)/(base)/account': {
      id: '/(authed)/(base)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authedbaseAccountRouteRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
    '/(authed)/(base)/play': {
      id: '/(authed)/(base)/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof authedbasePlayRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
    '/(authed)/(base)/play-grader': {
      id: '/(authed)/(base)/play-grader'
      path: '/play-grader'
      fullPath: '/play-grader'
      preLoaderRoute: typeof authedbasePlayGraderRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
    '/(authed)/session/$id': {
      id: '/(authed)/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof authedSessionIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/admin/course/': {
      id: '/admin/course/'
      path: '/course'
      fullPath: '/admin/course/'
      preLoaderRoute: typeof AdminCourseIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/course/$id': {
      id: '/admin/course/$id'
      path: '/course/$id'
      fullPath: '/admin/course/$id'
      preLoaderRoute: typeof AdminCourseIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/course/create': {
      id: '/admin/course/create'
      path: '/course/create'
      fullPath: '/admin/course/create'
      preLoaderRoute: typeof AdminCourseCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/user'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user/$id': {
      id: '/admin/user/$id'
      path: '/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof AdminUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(authed)/(base)/account/': {
      id: '/(authed)/(base)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof authedbaseAccountIndexRouteImport
      parentRoute: typeof authedbaseAccountRouteRoute
    }
    '/(authed)/(base)/account/security': {
      id: '/(authed)/(base)/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof authedbaseAccountSecurityRouteImport
      parentRoute: typeof authedbaseAccountRouteRoute
    }
    '/(authed)/(base)/account/transactions': {
      id: '/(authed)/(base)/account/transactions'
      path: '/transactions'
      fullPath: '/account/transactions'
      preLoaderRoute: typeof authedbaseAccountTransactionsRouteImport
      parentRoute: typeof authedbaseAccountRouteRoute
    }
    '/(authed)/(base)/lesson/$lessonId': {
      id: '/(authed)/(base)/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof authedbaseLessonLessonIdRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
    '/(authed)/(base)/profile/$username': {
      id: '/(authed)/(base)/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof authedbaseProfileUsernameRouteImport
      parentRoute: typeof authedbaseRouteRoute
    }
  }
}

interface authedbaseAccountRouteRouteChildren {
  authedbaseAccountSecurityRoute: typeof authedbaseAccountSecurityRoute
  authedbaseAccountTransactionsRoute: typeof authedbaseAccountTransactionsRoute
  authedbaseAccountIndexRoute: typeof authedbaseAccountIndexRoute
}

const authedbaseAccountRouteRouteChildren: authedbaseAccountRouteRouteChildren =
  {
    authedbaseAccountSecurityRoute: authedbaseAccountSecurityRoute,
    authedbaseAccountTransactionsRoute: authedbaseAccountTransactionsRoute,
    authedbaseAccountIndexRoute: authedbaseAccountIndexRoute,
  }

const authedbaseAccountRouteRouteWithChildren =
  authedbaseAccountRouteRoute._addFileChildren(
    authedbaseAccountRouteRouteChildren,
  )

interface authedbaseRouteRouteChildren {
  authedbaseAccountRouteRoute: typeof authedbaseAccountRouteRouteWithChildren
  authedbasePlayRoute: typeof authedbasePlayRoute
  authedbasePlayGraderRoute: typeof authedbasePlayGraderRoute
  authedbaseIndexRoute: typeof authedbaseIndexRoute
  authedbaseLessonLessonIdRoute: typeof authedbaseLessonLessonIdRoute
  authedbaseProfileUsernameRoute: typeof authedbaseProfileUsernameRoute
}

const authedbaseRouteRouteChildren: authedbaseRouteRouteChildren = {
  authedbaseAccountRouteRoute: authedbaseAccountRouteRouteWithChildren,
  authedbasePlayRoute: authedbasePlayRoute,
  authedbasePlayGraderRoute: authedbasePlayGraderRoute,
  authedbaseIndexRoute: authedbaseIndexRoute,
  authedbaseLessonLessonIdRoute: authedbaseLessonLessonIdRoute,
  authedbaseProfileUsernameRoute: authedbaseProfileUsernameRoute,
}

const authedbaseRouteRouteWithChildren = authedbaseRouteRoute._addFileChildren(
  authedbaseRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedbaseRouteRoute: typeof authedbaseRouteRouteWithChildren
  authedSessionIdRoute: typeof authedSessionIdRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedbaseRouteRoute: authedbaseRouteRouteWithChildren,
  authedSessionIdRoute: authedSessionIdRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCourseIdRoute: typeof AdminCourseIdRoute
  AdminCourseCreateRoute: typeof AdminCourseCreateRoute
  AdminUserIdRoute: typeof AdminUserIdRoute
  AdminCourseIndexRoute: typeof AdminCourseIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCourseIdRoute: AdminCourseIdRoute,
  AdminCourseCreateRoute: AdminCourseCreateRoute,
  AdminUserIdRoute: AdminUserIdRoute,
  AdminCourseIndexRoute: AdminCourseIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedRouteRoute: authedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
