/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const button: string;
declare const primary: string;
declare const secondary: string;
declare const ghost: string;
declare const sizeXs: string;
declare const sizeSm: string;
declare const sizeMd: string;
declare const sizeLg: string;
declare const block: string;
declare const pilled: string;
declare const square: string;

export {
	button,
	primary,
	secondary,
	ghost,
	block,
	pilled,
	square
};

declare const __default_export__: {
	button: typeof button;
	primary: typeof primary;
	secondary: typeof secondary;
	ghost: typeof ghost;
	"size-xs": typeof sizeXs;
	"size-sm": typeof sizeSm;
	"size-md": typeof sizeMd;
	"size-lg": typeof sizeLg;
	block: typeof block;
	pilled: typeof pilled;
	square: typeof square;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYnV0dG9uLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYnV0dG9uLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FFQTtjQStCRztjQU1BO2NBTUE7Y0FNQTtjQUtBO2NBS0E7Y0FLQTtjQUtBO2NBSUE7Y0FJQTs7O0NBN0VIO0NBK0JHO0NBTUE7Q0FNQTtDQTBCQTtDQUlBO0NBSUE7Ozs7Q0E3RUg7Q0ErQkc7Q0FNQTtDQU1BOzs7OztDQTBCQTtDQUlBO0NBSUE7OyJ9
