/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const logo: string;

export {
	logo
};

declare const __default_export__: {
	logo: typeof logo;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibG9nby5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImxvZ28ubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUVBOzs7Q0FBQTs7OztDQUFBOzsifQ==
