/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const trigger: string;
declare const popup: string;
declare const item: string;
declare const separator: string;

export {
	trigger,
	popup,
	item,
	separator
};

declare const __default_export__: {
	trigger: typeof trigger;
	popup: typeof popup;
	item: typeof item;
	separator: typeof separator;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZHJvcGRvd24ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJkcm9wZG93bi5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FZQTtjQWtDQTtjQTZCQTs7O0NBM0VBO0NBWUE7Q0FrQ0E7Q0E2QkE7Ozs7Q0EzRUE7Q0FZQTtDQWtDQTtDQTZCQTs7In0=
