/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const navbar: string;
declare const container: string;
declare const navigationContent: string;
declare const navigationItems: string;
declare const userProfile: string;
declare const badge: string;

export {
	navbar,
	container,
	navigationContent as "navigation-content",
	navigationItems as "navigation-items",
	userProfile as "user-profile",
	badge
};

declare const __default_export__: {
	navbar: typeof navbar;
	container: typeof container;
	"navigation-content": typeof navigationContent;
	"navigation-items": typeof navigationItems;
	"user-profile": typeof userProfile;
	badge: typeof badge;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibmF2YmFyLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsibmF2YmFyLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FFQTtjQUdFO2NBV0U7Y0FLRTtjQVVGO2NBS0U7OztDQWxDTjtDQUdFO0NBV0U7Q0FLRTtDQVVGO0NBS0U7Ozs7Q0FsQ047Q0FHRTs7OztDQStCSTs7In0=
