name: Checker

on:
  push:
    branches: [feat/*, bug/*, develop]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check:
    name: Lint, Format & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci

      - name: Run Type Check
        run: npm run ts:check

      - name: Run Linter
        run: npm run lint

      - name: Run Format Check
        run: npm run format:check
